### ISSUE TITLE
Adjustable Rotation Rate

### ISSUE THREAD

**Issue by faelin** [getsenic/nuimo-swift#4]
Please allow adjustability of responsiveness to rotation (i.e. what mouse drivers call "scroll speed"), so that actions like shortcut key-commands (e.g. ⌘⇥ or other) can be performed more rapidly. Best possible option would be a responsiveness-curve, so that users could have the ring send the shortcut periodically when rotating slowly, and rapidly increase the frequency with which the signal is sent as the user spins faster, so that the user could exceed their own maximum ability to spin the ring (which moves slowly due to friction).

**Comment by larsblumberg** [comment]
Hi @faelin! Does your suggestion concern the macOS app? We're indeed planning to add an acceleration feature that will speed commands in case you keep rotating the wheel. As I understand this is what you're looking for?

**Comment by faelin** [comment]
Although this is not specifically a Mac OS X feature, it was suggested by a
user on the Facebook page that I post here. Please feel free to move this
request to a more relevant section.

**Comment by larsblumberg** [comment]
Thanks @faelin – the acceleration that you're describing needs to be implemented in the app that connects to Nuimo (it will no become part of Nuimo). It's planned to come to the macOS app with one of the next updates. Thanks for sharing this issue with us.
